config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :todos, only: [:index, :new, :create ,:show] do
    resource :completion, only: :create
  end
  root to: "home#index"
  resources :users
  resource :session, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  def completed?
    completed_at?
  end
end

app/models/user.rb
class User < ApplicationRecord
  scope :active_users, -> {where(active: true)}
  scope :inactive_users, -> {where(active: false)}
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authenticate
    if !signed_in?
    redirect_to new_session_path
    end
  end

  def signed_in?
    current_user.signed_in?
  end


  def sign_in_as(email)
    session[:current_email] = email
  end

  def current_user
    Yser.new(session[:current_email])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate

  def index
    @todos ||= current_user.todos
  end

  def new
    @todo = Todo.new
  end

  def create
    current_user.todos.create(todo_params)
    redirect_to todos_path
  end

  def show
    @todo = Todo.find(params[:id])
  end

  private
  def todo_params
    params.require(:todo).permit(:title)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Features</h1>
<ul class="feature">
  <li><%= link_to "todo application", todos_path %></li>
  <li><%= link_to "User application", users_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/index.html.erb
<h1>Hello User</h1>
<%= link_to "add todo", new_todo_path %>

<table class="todo">
  <thead>
    <tr>
      <th>TASK</th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td class="<%="completed" if todo.completed? %>">
          <%= todo.title %>
          <%= button_to 'mark complete', todo_completion_path(todo) %>
          <%= link_to 'Show', todo %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/todos/new.html.erb
<%= form_for @todo do |form| %>
<%= form.label :title %>
<%= form.text_field :title %>
<%= form.submit "Submit" %>
<% end %>